# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_messagebox.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(954, 690)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/Baykuş.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonCritical = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCritical.setGeometry(QtCore.QRect(90, 80, 111, 111))
        self.pushButtonCritical.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/critical.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonCritical.setIcon(icon1)
        self.pushButtonCritical.setIconSize(QtCore.QSize(70, 70))
        self.pushButtonCritical.setObjectName("pushButtonCritical")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 220, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setObjectName("label")
        self.pushButtonInfo = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonInfo.setGeometry(QtCore.QRect(280, 80, 111, 111))
        self.pushButtonInfo.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/Info.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonInfo.setIcon(icon2)
        self.pushButtonInfo.setIconSize(QtCore.QSize(70, 70))
        self.pushButtonInfo.setObjectName("pushButtonInfo")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 220, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setObjectName("label_2")
        self.pushButtonQuestion = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonQuestion.setGeometry(QtCore.QRect(490, 80, 111, 111))
        self.pushButtonQuestion.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/question.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonQuestion.setIcon(icon3)
        self.pushButtonQuestion.setIconSize(QtCore.QSize(70, 70))
        self.pushButtonQuestion.setObjectName("pushButtonQuestion")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(500, 220, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setObjectName("label_3")
        self.pushButtonWarning = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonWarning.setGeometry(QtCore.QRect(710, 80, 111, 111))
        self.pushButtonWarning.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/warning.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonWarning.setIcon(icon4)
        self.pushButtonWarning.setIconSize(QtCore.QSize(70, 70))
        self.pushButtonWarning.setObjectName("pushButtonWarning")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(720, 220, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setObjectName("label_4")
        self.pushButtonOzel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonOzel.setGeometry(QtCore.QRect(580, 360, 111, 111))
        self.pushButtonOzel.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon/Numbers.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonOzel.setIcon(icon5)
        self.pushButtonOzel.setIconSize(QtCore.QSize(70, 70))
        self.pushButtonOzel.setObjectName("pushButtonOzel")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(590, 500, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(710, 400, 191, 51))
        self.comboBox.setObjectName("comboBox")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(740, 340, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setObjectName("label_6")
        self.pushButtonAbautQT = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAbautQT.setGeometry(QtCore.QRect(260, 350, 111, 111))
        self.pushButtonAbautQT.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icon/Turkey.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonAbautQT.setIcon(icon6)
        self.pushButtonAbautQT.setIconSize(QtCore.QSize(70, 70))
        self.pushButtonAbautQT.setObjectName("pushButtonAbautQT")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(270, 490, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setFrameShape(QtWidgets.QFrame.Box)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(50, 490, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setFrameShape(QtWidgets.QFrame.Box)
        self.label_8.setObjectName("label_8")
        self.pushButtonY40 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonY40.setGeometry(QtCore.QRect(40, 350, 111, 111))
        self.pushButtonY40.setText("")
        self.pushButtonY40.setIcon(icon)
        self.pushButtonY40.setIconSize(QtCore.QSize(70, 70))
        self.pushButtonY40.setObjectName("pushButtonY40")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 954, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "critical"))
        self.label_2.setText(_translate("MainWindow", "information"))
        self.label_3.setText(_translate("MainWindow", "question"))
        self.label_4.setText(_translate("MainWindow", "warning"))
        self.label_5.setText(_translate("MainWindow", "özel kullanım"))
        self.label_6.setText(_translate("MainWindow", "sayılar:"))
        self.label_7.setText(_translate("MainWindow", "about QT"))
        self.label_8.setText(_translate("MainWindow", "Y40 hakkında"))
